// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calc_betas
SEXP calc_betas(SEXP y);
RcppExport SEXP RReserving_calc_betas(SEXP ySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type y(ySEXP );
        SEXP __result = calc_betas(y);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// chainladder
SEXP chainladder(SEXP tri, SEXP wghts, SEXP alpha, SEXP tail, SEXP tail_se, SEXP tail_sigma);
RcppExport SEXP RReserving_chainladder(SEXP triSEXP, SEXP wghtsSEXP, SEXP alphaSEXP, SEXP tailSEXP, SEXP tail_seSEXP, SEXP tail_sigmaSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type tri(triSEXP );
        Rcpp::traits::input_parameter< SEXP >::type wghts(wghtsSEXP );
        Rcpp::traits::input_parameter< SEXP >::type alpha(alphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type tail(tailSEXP );
        Rcpp::traits::input_parameter< SEXP >::type tail_se(tail_seSEXP );
        Rcpp::traits::input_parameter< SEXP >::type tail_sigma(tail_sigmaSEXP );
        SEXP __result = chainladder(tri, wghts, alpha, tail, tail_se, tail_sigma);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
