# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_betas <- function(y) {
    .Call('RReserving_calc_betas', PACKAGE = 'RReserving', y)
}

chainladder_ <- function(tri, wghts, alpha, tail, tail_se, tail_sigma) {
    .Call('RReserving_chainladder', PACKAGE = 'RReserving', tri, wghts, alpha, tail, tail_se, tail_sigma)
}

